import { readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join, extname, relative } from "node:path";

const CWD = process.cwd();

const MIME_TYPES = {
  ".html": "text/html",
  ".js": "application/javascript",
  ".css": "text/css",
  ".json": "application/json",
  ".png": "image/png",
  ".svg": "image/svg+xml",
  ".ico": "image/x-icon",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".ttf": "font/ttf",
  ".eot": "application/vnd.ms-fontobject",
};

const PC_ADMIN_DIST = join(process.cwd(), "pc-admin", "dist");
const OUTPUT = join(process.cwd(), "backend", "src", "worker", "static-files.js");

const files = new Map();

function walk(dir, prefix = "") {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    const stat = statSync(full);
    if (stat.isDirectory()) {
      walk(full, prefix === "" ? entry : prefix + "/" + entry);
    } else {
      const rel =
        prefix === "" ? `/${entry}` : `/${prefix}/${entry}`;
      const body = readFileSync(full);
      const contentType = MIME_TYPES[extname(rel).toLowerCase()] || "application/octet-stream";
      files.set(rel, { contentType, body: Buffer.from(body) });
    }
  }
}

walk(PC_ADMIN_DIST);

// Generate JS module with base64-encoded files
let output = "// Auto-generated by build-static.js - DO NOT EDIT\n";
output += "const FILES = new Map([\n";

for (const [path, { contentType, body }] of files) {
  const base64 = body.toString("base64");
  output += `  ["${path}", { contentType: "${contentType}", body: Uint8Array.from(atob("${base64}"), c => c.charCodeAt(0)) }],\n`;
}

output += "]);\n\n";
output += "export function getStaticFile(path) {\n";
output += "  let file = FILES.get(path);\n";
output += '  if (!file && !path.includes(".")) {\n';
output += '    file = FILES.get("/index.html");\n';
output += "  }\n";
output += "  return file || null;\n";
output += "}\n";
output += `export const STATIC_FILE_COUNT = ${files.size};\n`;

writeFileSync(OUTPUT, output);
console.log(`Generated ${files.size} static files -> ${relative(PC_ADMIN_DIST, OUTPUT)}`);
