comment on database tcm_clinic is '中医馆预约、健康档案、内容运营与管理后台业务数据库';

comment on table users is '用户与会员账户表，包含微信身份、会员信息、后台角色与邀请关系';
comment on column users.id is '用户主键 ID';
comment on column users.openid is '微信或小程序平台用户唯一标识';
comment on column users.nickname is '用户昵称';
comment on column users.phone is '用户手机号';
comment on column users.avatar_url is '用户头像 URL';
comment on column users.member_level is '会员等级名称';
comment on column users.points is '会员积分余额';
comment on column users.admin_role is '后台角色，member/frontdesk/manager/owner 等';
comment on column users.can_manage is '是否允许显示和访问管理入口';
comment on column users.invited_by is '邀请人用户 ID';
comment on column users.created_at is '用户创建时间';
comment on column users.updated_at is '用户资料更新时间';

comment on table stores is '门店表，维护中医馆门店基础信息、位置、营业时间与启停状态';
comment on column stores.id is '门店主键 ID';
comment on column stores.name is '门店名称';
comment on column stores.city is '门店所在城市';
comment on column stores.address is '门店详细地址';
comment on column stores.phone is '门店联系电话';
comment on column stores.business_hours is '门店营业时间说明';
comment on column stores.latitude is '门店纬度坐标';
comment on column stores.longitude is '门店经度坐标';
comment on column stores.is_default is '是否默认门店';
comment on column stores.status is '门店状态，active 启用，inactive 停用';
comment on column stores.created_at is '门店创建时间';
comment on column stores.updated_at is '门店更新时间';

comment on table family_members is '家庭成员表，用户可为本人或家属预约和维护健康档案';
comment on column family_members.id is '家庭成员主键 ID';
comment on column family_members.user_id is '所属用户 ID';
comment on column family_members.name is '家庭成员姓名';
comment on column family_members.relation is '与用户关系，如本人、父母、子女等';
comment on column family_members.gender is '性别，unknown 表示未填写';
comment on column family_members.birthday is '出生日期';
comment on column family_members.phone is '家庭成员联系电话';
comment on column family_members.created_at is '家庭成员创建时间';

comment on table services is '服务项目表，维护可预约的中医理疗、问诊、艾灸等项目';
comment on column services.id is '服务项目主键 ID';
comment on column services.store_id is '所属门店 ID，为空表示通用项目';
comment on column services.name is '项目名称';
comment on column services.category is '项目分类';
comment on column services.description is '项目说明';
comment on column services.duration_minutes is '服务时长，单位分钟';
comment on column services.price is '项目销售价格';
comment on column services.cover_url is '项目封面图 URL';
comment on column services.sort_order is '展示排序值，越大越靠前';
comment on column services.is_active is '是否上架可预约';
comment on column services.created_at is '项目创建时间';

comment on table practitioners is '技师/医师档案表，维护服务人员资质、擅长方向和状态';
comment on column practitioners.id is '技师主键 ID';
comment on column practitioners.store_id is '默认所属门店 ID';
comment on column practitioners.name is '技师姓名';
comment on column practitioners.title is '职称或岗位头衔';
comment on column practitioners.avatar_url is '技师头像 URL';
comment on column practitioners.bio is '技师简介';
comment on column practitioners.specialties is '擅长方向标签数组';
comment on column practitioners.certificates is '证书或资质信息 JSON 数组';
comment on column practitioners.rating is '展示评分';
comment on column practitioners.status is '技师状态，active 在职，resting 休息，inactive 隐藏或离职';
comment on column practitioners.created_at is '技师创建时间';

comment on table practitioner_stores is '技师与门店关联表，支持技师多门店执业';
comment on column practitioner_stores.practitioner_id is '技师 ID';
comment on column practitioner_stores.store_id is '门店 ID';
comment on column practitioner_stores.is_primary is '是否该技师的主门店';

comment on table practitioner_services is '技师与服务项目关联表，表示技师可提供哪些项目';
comment on column practitioner_services.practitioner_id is '技师 ID';
comment on column practitioner_services.service_id is '服务项目 ID';

comment on table schedules is '排班表，维护技师在指定门店、日期和时间段的可预约容量';
comment on column schedules.id is '排班主键 ID';
comment on column schedules.store_id is '排班所属门店 ID';
comment on column schedules.practitioner_id is '排班技师 ID';
comment on column schedules.work_date is '排班日期';
comment on column schedules.start_time is '开始时间';
comment on column schedules.end_time is '结束时间';
comment on column schedules.capacity is '该时间段可预约容量';
comment on column schedules.status is '排班状态，open 可约，closed 关闭';
comment on column schedules.created_at is '排班创建时间';

comment on table appointments is '预约订单表，记录用户预约项目、技师、排班、支付与核销状态';
comment on column appointments.id is '预约订单主键 ID';
comment on column appointments.order_no is '业务订单号';
comment on column appointments.store_id is '预约门店 ID';
comment on column appointments.user_id is '预约用户 ID';
comment on column appointments.family_member_id is '被服务的家庭成员 ID，为空表示用户本人';
comment on column appointments.service_id is '预约服务项目 ID';
comment on column appointments.practitioner_id is '预约技师 ID';
comment on column appointments.schedule_id is '关联排班 ID';
comment on column appointments.appointment_date is '预约日期';
comment on column appointments.start_time is '预约开始时间';
comment on column appointments.end_time is '预约结束时间';
comment on column appointments.amount is '订单应付金额';
comment on column appointments.status is '预约状态，pending/confirmed/completed/cancelled/refunded';
comment on column appointments.payment_status is '支付状态，unpaid/paid/refunded 等';
comment on column appointments.note is '用户预约备注';
comment on column appointments.verification_code is '到店核销码';
comment on column appointments.created_at is '订单创建时间';
comment on column appointments.updated_at is '订单更新时间';

comment on table commission_rules is '提成规则表，按项目、技师和业绩门槛配置提成比例';
comment on column commission_rules.id is '提成规则主键 ID';
comment on column commission_rules.name is '规则名称';
comment on column commission_rules.service_id is '适用服务项目 ID，空表示全部项目';
comment on column commission_rules.practitioner_id is '适用技师 ID，空表示全部技师';
comment on column commission_rules.threshold_amount is '业绩门槛金额';
comment on column commission_rules.rate is '提成比例，例如 0.18 表示 18%';
comment on column commission_rules.status is '规则状态，active 启用，inactive 停用';
comment on column commission_rules.created_at is '规则创建时间';

comment on table commission_settlements is '提成结算单表，记录技师在一个周期内的业绩和应结提成';
comment on column commission_settlements.id is '结算单主键 ID';
comment on column commission_settlements.practitioner_id is '结算技师 ID';
comment on column commission_settlements.period_start is '结算周期开始日期';
comment on column commission_settlements.period_end is '结算周期结束日期';
comment on column commission_settlements.gross_amount is '周期内总业绩金额';
comment on column commission_settlements.commission_amount is '周期内应结提成金额';
comment on column commission_settlements.status is '结算状态，pending/settled 等';
comment on column commission_settlements.created_at is '结算单创建时间';

comment on table activities is '营销活动表，用于首页或内容营销位展示活动商品和促销信息';
comment on column activities.id is '活动主键 ID';
comment on column activities.store_id is '活动所属门店 ID，空表示全局活动';
comment on column activities.title is '活动标题';
comment on column activities.subtitle is '活动副标题';
comment on column activities.cover_url is '活动封面图 URL';
comment on column activities.price is '活动价';
comment on column activities.original_price is '原价';
comment on column activities.tag is '活动标签，如新客专享';
comment on column activities.starts_at is '活动开始时间';
comment on column activities.ends_at is '活动结束时间';
comment on column activities.sort_order is '展示排序值，越大越靠前';
comment on column activities.is_active is '活动是否启用展示';
comment on column activities.created_at is '活动创建时间';

comment on table articles is '养生资讯文章表，用于内容营销和健康科普展示';
comment on column articles.id is '文章主键 ID';
comment on column articles.store_id is '文章所属门店 ID，空表示全局文章';
comment on column articles.title is '文章标题';
comment on column articles.summary is '文章摘要';
comment on column articles.content is '文章正文内容';
comment on column articles.cover_url is '文章封面图 URL';
comment on column articles.category is '文章分类';
comment on column articles.read_minutes is '预计阅读分钟数';
comment on column articles.status is '文章状态，draft 草稿，published 已发布';
comment on column articles.published_at is '发布时间';

comment on table coupons is '用户优惠券表，记录优惠券金额、使用门槛、状态与有效期';
comment on column coupons.id is '优惠券主键 ID';
comment on column coupons.user_id is '所属用户 ID';
comment on column coupons.title is '优惠券名称';
comment on column coupons.amount is '优惠金额';
comment on column coupons.min_spend is '最低消费门槛';
comment on column coupons.status is '优惠券状态，unused/used/expired 等';
comment on column coupons.expires_at is '优惠券过期时间';
comment on column coupons.created_at is '优惠券创建时间';

comment on table health_records is '健康档案表，记录用户体质、症状、舌诊图片、脉象和诊断建议';
comment on column health_records.id is '健康档案主键 ID';
comment on column health_records.user_id is '所属用户 ID';
comment on column health_records.constitution is '中医体质类型';
comment on column health_records.symptoms is '症状标签数组';
comment on column health_records.tongue_image_url is '舌诊图片 URL';
comment on column health_records.pulse_note is '脉象记录';
comment on column health_records.diagnosis_note is '诊断或调理建议';
comment on column health_records.created_at is '健康档案创建时间';

comment on table homepage_configs is '首页配置表，按门店配置首页模块、标题、排序和 JSON 内容';
comment on column homepage_configs.id is '首页配置主键 ID';
comment on column homepage_configs.store_id is '配置所属门店 ID，空表示全局配置';
comment on column homepage_configs.section_key is '首页模块标识，如 hero、services、articles';
comment on column homepage_configs.title is '模块展示标题';
comment on column homepage_configs.payload is '模块 JSON 配置内容';
comment on column homepage_configs.sort_order is '模块排序值，越大越靠前';
comment on column homepage_configs.is_active is '配置是否启用';
comment on column homepage_configs.created_at is '配置创建时间';
comment on column homepage_configs.updated_at is '配置更新时间';

comment on table reviews is '用户评价表，记录预约评价、门店回复和展示状态';
comment on column reviews.id is '评价主键 ID';
comment on column reviews.appointment_id is '关联预约订单 ID';
comment on column reviews.user_id is '评价用户 ID';
comment on column reviews.practitioner_id is '被评价技师 ID';
comment on column reviews.store_id is '被评价门店 ID';
comment on column reviews.rating is '评分，1 到 5 分';
comment on column reviews.content is '评价内容';
comment on column reviews.reply is '门店或后台回复内容';
comment on column reviews.status is '评价状态，visible 显示，hidden 隐藏';
comment on column reviews.created_at is '评价创建时间';

comment on table admin_audit_logs is '后台操作日志表，记录管理员操作行为、目标对象和详情';
comment on column admin_audit_logs.id is '操作日志主键 ID';
comment on column admin_audit_logs.user_id is '操作人用户 ID';
comment on column admin_audit_logs.action is '操作动作标识';
comment on column admin_audit_logs.target_type is '操作目标类型';
comment on column admin_audit_logs.target_id is '操作目标 ID';
comment on column admin_audit_logs.detail is '操作详情 JSON';
comment on column admin_audit_logs.created_at is '操作发生时间';
